project:
  type: book



book:
  title: "The jewel in the garden"
  author: "bhangakhana"
  date: "10/9/2025"
  chapters:
    - index.qmd
    - One.qmd
    - Two.qmd
    - Three.qmd
    - summary.qmd
    - references.qmd


bibliography: references.bib
zotero: true

format:
  html:
    theme:
      - sandstone
      - brand
  pdf:
    documentclass: scrreprt

execute:
   freeze: auto






