project:
  type: book



book:
  title: "The jewel in the garden"
  author: "bhangakhana"
  date: "10/9/2025"
#  cover-image: images/logo3.png
  favicon: images/favicon.ico
  navbar:
    search: true
    logo: images/logo3.png
  sidebar:
    logo: images/logo3.png
  chapters:
    - index.qmd
    - One.qmd
    - Two.qmd
    - Three.qmd
    - summary.qmd
    - references.qmd
  downloads: [pdf, epub]


bibliography: references.bib
zotero: true

format:
  html:
    theme:
      - sandstone
      - brand
  pdf:
    documentclass: scrreprt
  epub:
    documentclass: scrreprt

execute:
   freeze: auto






